views:
  - id: dashboard
    title: "Medication Registry Dashboard"
    blocks:
      - type: markdown
        content: |
          # Medication Registry

          This dashboard demonstrates FHIRPath-indexed queries over a large
          medication dataset sourced from RxNorm. Each box below is driven by a
          FHIRPath expression evaluated at build time and materialized into SQLite
          for fast runtime queries.

      # Box 1: Oral Solid Medications (Tablets & Capsules) with status filter
      - type: fhirpath-table
        title: "Oral Solid Medications"
        description: "Tablets and capsules - filter by status"
        expression: "Medication.where(form.coding.display in ('Tablet' | 'Capsule'))"
        variables:
          - name: status
            type: filter
            label: "Status"
            optionsExpression: "Medication.status.distinct()"
            valueExpression: "status"
        columns:
          - header: "Name"
            path: "code.text"
          - header: "Form"
            path: "form.coding.first().display"
          - header: "Status"
            path: "status"
        pageSize: 10

      # Box 2: Injectable/Solution Medications
      - type: fhirpath-table
        title: "Solutions & Injectables"
        description: "Solutions and prefilled syringes - filter by status"
        expression: "Medication.where(form.coding.display in ('Solution' | 'Prefilled syringe'))"
        variables:
          - name: status
            type: filter
            label: "Status"
            optionsExpression: "Medication.status.distinct()"
            valueExpression: "status"
        columns:
          - header: "Name"
            path: "code.text"
          - header: "Form"
            path: "form.coding.first().display"
          - header: "RxNorm Code"
            path: "code.coding.where(system='http://www.nlm.nih.gov/research/umls/rxnorm').first().code"
        pageSize: 10

      # Box 3: Topical Medications with form filter
      - type: fhirpath-table
        title: "Topical Medications"
        description: "Ointments, creams, gels, lotions - filter by specific form"
        expression: "Medication.where(form.coding.display in ('Ointment' | 'Cream' | 'Gel' | 'Lotion'))"
        variables:
          - name: form
            type: filter
            label: "Form"
            optionsExpression: "Medication.where(form.coding.display in ('Ointment' | 'Cream' | 'Gel' | 'Lotion')).form.coding.display.distinct()"
            valueExpression: "form.coding.first().display"
        columns:
          - header: "Name"
            path: "code.text"
          - header: "Form"
            path: "form.coding.first().display"
          - header: "Status"
            path: "status"
        pageSize: 10

      # Box 4: Suspensions with status filter
      - type: fhirpath-table
        title: "Suspensions"
        description: "Oral and injectable suspensions"
        expression: "Medication.where(form.coding.display = 'Suspension')"
        variables:
          - name: status
            type: filter
            label: "Status"
            optionsExpression: "Medication.status.distinct()"
            valueExpression: "status"
        columns:
          - header: "Name"
            path: "code.text"
          - header: "Form"
            path: "form.coding.first().display"
          - header: "Status"
            path: "status"
        pageSize: 10

      # Box 5: All Medications with multiple filters
      - type: fhirpath-table
        title: "All Medications (Filterable)"
        description: "Complete medication list with status and form filters"
        expression: "Medication"
        variables:
          - name: status
            type: filter
            label: "Status"
            optionsExpression: "Medication.status.distinct()"
            valueExpression: "status"
          - name: form
            type: filter
            label: "Dose Form"
            optionsExpression: "Medication.form.coding.display.distinct()"
            valueExpression: "form.coding.first().display"
        columns:
          - header: "ID"
            path: "id"
          - header: "Name"
            path: "code.text"
          - header: "Status"
            path: "status"
          - header: "Form"
            path: "form.coding.first().display"
          - header: "Has Ingredients"
            path: "ingredient.exists()"
        pageSize: 15

  - id: rxnorm-codes
    title: "RxNorm Code Browser"
    blocks:
      - type: markdown
        content: |
          # RxNorm Code Browser

          Browse all RxNorm codes in the medication registry. Each medication
          is identified by a unique RxNorm Concept Unique Identifier (RXCUI).

      - type: fhirpath-table
        title: "RxNorm Codes"
        description: "All RxNorm medication codes"
        expression: "Medication.code.coding"
        columns:
          - header: "RxNorm Code"
            path: "code"
          - header: "Display Name"
            path: "display"
          - header: "System"
            path: "system"
        pageSize: 25

  - id: ingredients
    title: "Ingredient Analysis"
    blocks:
      - type: markdown
        content: |
          # Medication Ingredients

          Analysis of active ingredients across the medication registry.
          Ingredient data is derived from RxNorm component relationships.

      - type: fhirpath-table
        title: "All Ingredients"
        description: "Ingredient entries from medications that have them"
        expression: "Medication.ingredient"
        columns:
          - header: "Ingredient"
            path: "itemCodeableConcept.coding.first().display"
          - header: "Strength"
            path: "strength.numerator.value"
          - header: "Unit"
            path: "strength.numerator.unit"
        pageSize: 20

  - id: manufacturers
    title: "Manufacturer Analysis"
    blocks:
      - type: markdown
        content: |
          # Medication Manufacturers

          Analysis of manufacturers represented in the medication registry.

      - type: fhirpath-table
        title: "Medications by Manufacturer"
        description: "Filter medications by manufacturer"
        expression: "Medication.where(manufacturer.exists())"
        variables:
          - name: manufacturer
            type: filter
            label: "Manufacturer"
            optionsExpression: "Medication.manufacturer.display.distinct()"
            valueExpression: "manufacturer.display"
        columns:
          - header: "Name"
            path: "code.text"
          - header: "Form"
            path: "form.coding.first().display"
          - header: "Manufacturer"
            path: "manufacturer.display"
        pageSize: 15
